[build]
  command = "npm run build:netlify"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.5.1"
  
[dev]
  command = "npm run dev"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 