[build]
  command = "npm run build:netlify"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.5.1"
  
[dev]
  command = "npm run dev"
  
# Redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate''' 