export default defineEventHandler(() => {
  return [
    {
      id: 'paris-gala',
      title: 'Noite de Gala em Paris',
      subtitle: 'Uma experiência exclusiva com nossa modelo especialista em eventos',
      image: '/images/experiences/cocktail.jpg',
      modelName: 'Anfitriã Premium',
      modelDescription: 'Especialista em eventos de gala com mais de 8 anos de experiência internacional e presença constante em eventos de alta classe em Paris e Milão.',
      modelProfileImage: '/images/experiences/cocktail.jpg',
      ticketsSold: 78,
      totalTickets: 100,
      raffleTimeRemaining: '2 dias 14 horas',
      daysRemaining: 3,
      isNew: true,
      heroImage: '/images/experiences/cocktail.jpg',
      parallaxBackground: '/images/experiences/wine.jpg',
      longDescription: 'Uma noite inesquecível em Paris, com acesso VIP aos melhores eventos e locais exclusivos da cidade luz. Acompanhe nossa anfitriã premium em uma jornada pelos restaurantes mais sofisticados, festas privadas e momentos únicos. Esta experiência inclui elementos surpresa personalizados e momentos memoráveis preparados especialmente para tornar sua visita a Paris verdadeiramente mágica.',
      contentPreviews: [
        { title: 'Momentos Exclusivos', thumbnail: '/images/experiences/cocktail.jpg' },
        { title: 'Gastronomia Premium', thumbnail: '/images/experiences/wine.jpg' },
        { title: 'Eventos Especiais', thumbnail: '/images/experiences/gatsby.jpg' },
        { title: 'Passeios Privados', thumbnail: '/images/experiences/escape.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/wine.jpg',
      raffleMainPrizeDescription: 'Passe VIP para evento exclusivo em Paris com acompanhamento personalizado de nossa anfitriã premium',
      features: [
        { title: 'Acesso VIP', description: 'Entrada exclusiva em todos os eventos', icon: '/images/icons/vip.svg' },
        { title: 'Experiência Personalizada', description: 'Roteiro adaptado às suas preferências', icon: '/images/icons/custom.svg' },
        { title: 'Momentos Exclusivos', description: 'Oportunidades para registros fotográficos em locais privilegiados', icon: '/images/icons/camera.svg' },
      ]
    },
    {
      id: 'beach-photoshoot',
      title: 'Ensaio Fotográfico Exclusivo',
      subtitle: 'Experiência única com nossa modelo fotográfica',
      image: '/images/experiences/boudoir.jpg',
      modelName: 'Fotogênica Experience',
      modelDescription: 'Modelo fotográfica profissional com experiência em editoriais nacionais e internacionais, especialista em ensaios artísticos e conceituais.',
      modelProfileImage: '/images/experiences/boudoir.jpg',
      ticketsSold: 45,
      totalTickets: 100,
      raffleTimeRemaining: '5 dias 8 horas',
      daysRemaining: 5,
      isNew: false,
      heroImage: '/images/experiences/boudoir.jpg',
      parallaxBackground: '/images/experiences/escape.jpg',
      longDescription: 'Participe de um ensaio fotográfico exclusivo com nossa modelo profissional em um dos cenários mais deslumbrantes do Brasil. Acompanhe todo o processo criativo desde a concepção até a finalização, aprenda técnicas profissionais de fotografia e tenha a oportunidade de participar dos bastidores de uma produção de alto nível.',
      contentPreviews: [
        { title: 'Ensaio Artístico', thumbnail: '/images/experiences/boudoir.jpg' },
        { title: 'Bastidores', thumbnail: '/images/experiences/escape.jpg' },
        { title: 'Técnicas Fotográficas', thumbnail: '/images/experiences/gatsby.jpg' },
        { title: 'Momentos Criativos', thumbnail: '/images/experiences/qa.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/boudoir.jpg',
      raffleMainPrizeDescription: 'Um dia completo de ensaio fotográfico com equipe profissional e nossa modelo exclusiva',
      features: [
        { title: 'Acesso ao Set', description: 'Acompanhe todo o processo do ensaio fotográfico', icon: '/images/icons/camera.svg' },
        { title: 'Workshop Fotográfico', description: 'Aprenda técnicas profissionais de fotografia', icon: '/images/icons/chat.svg' },
        { title: 'Locação Exclusiva', description: 'Ambiente selecionado especialmente para a sessão', icon: '/images/icons/beach.svg' },
      ]
    },
    {
      id: 'yacht-party',
      title: 'Experiência Premium em Iate',
      subtitle: 'Navegue em grande estilo',
      image: '/images/experiences/escape.jpg',
      modelName: 'Anfitriã Náutica',
      modelDescription: 'Especialista em eventos náuticos de luxo, com formação em hospitalidade e vasta experiência em recepção VIP.',
      modelProfileImage: '/images/experiences/escape.jpg',
      ticketsSold: 62,
      totalTickets: 100,
      raffleTimeRemaining: '2 dias 5 horas',
      daysRemaining: 2,
      isNew: false,
      heroImage: '/images/experiences/escape.jpg',
      parallaxBackground: '/images/experiences/wine.jpg',
      longDescription: 'Uma experiência inesquecível a bordo de um iate de luxo. Navegue pelas águas cristalinas acompanhado de nossa anfitriã especializada, desfrute de bebidas premium, música exclusiva e momentos únicos. A experiência inclui paradas em pontos paradisíacos, atividades aquáticas e um serviço de catering de alta gastronomia.',
      contentPreviews: [
        { title: 'Tour pelo Iate', thumbnail: '/images/experiences/escape.jpg' },
        { title: 'Gastronomia a Bordo', thumbnail: '/images/experiences/wine.jpg' },
        { title: 'Pôr do Sol', thumbnail: '/images/experiences/cocktail.jpg' },
        { title: 'Atividades Exclusivas', thumbnail: '/images/experiences/poker.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/escape.jpg',
      raffleMainPrizeDescription: 'Passeio exclusivo de iate para você e 5 convidados com serviço premium completo',
      features: [
        { title: 'Bebidas Premium', description: 'Open bar com seleção de drinks exclusivos', icon: '/images/icons/drink.svg' },
        { title: 'Música Personalizada', description: 'Playlist selecionada de acordo com suas preferências', icon: '/images/icons/music.svg' },
        { title: 'Navegação Privada', description: 'Rota exclusiva com paradas em pontos paradisíacos', icon: '/images/icons/anchor.svg' },
      ]
    },
    {
      id: 'fashion-week',
      title: 'Bastidores da Moda',
      subtitle: 'Acesso VIP a evento de alta costura',
      image: '/images/experiences/gatsby.jpg',
      modelName: 'Fashion Insider',
      modelDescription: 'Modelo com carreira estabelecida no mundo da moda, participante regular das principais semanas de moda internacionais.',
      modelProfileImage: '/images/experiences/gatsby.jpg',
      ticketsSold: 30,
      totalTickets: 100,
      raffleTimeRemaining: '7 dias 12 horas',
      daysRemaining: 7,
      isNew: true,
      heroImage: '/images/experiences/gatsby.jpg',
      parallaxBackground: '/images/experiences/qa.jpg',
      longDescription: 'Tenha acesso exclusivo aos bastidores da Semana de Moda acompanhado por nossa modelo profissional. Acompanhe de perto a preparação, os desfiles e as festas exclusivas do evento mais importante do mundo da moda. Esta experiência única oferece a oportunidade de conhecer designers, fotógrafos e outros profissionais da indústria.',
      contentPreviews: [
        { title: 'Preparação', thumbnail: '/images/experiences/gatsby.jpg' },
        { title: 'Bastidores', thumbnail: '/images/experiences/qa.jpg' },
        { title: 'Desfiles', thumbnail: '/images/experiences/cocktail.jpg' },
        { title: 'After Party', thumbnail: '/images/experiences/wine.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/gatsby.jpg',
      raffleMainPrizeDescription: 'Acesso VIP a evento de moda exclusivo com nossa anfitriã especializada',
      features: [
        { title: 'Acesso aos Bastidores', description: 'Entre nos espaços restritos dos eventos', icon: '/images/icons/pass.svg' },
        { title: 'Networking', description: 'Oportunidade de conhecer profissionais da indústria', icon: '/images/icons/network.svg' },
        { title: 'Experiência Completa', description: 'Participação em todas as etapas do evento', icon: '/images/icons/calendar.svg' },
      ]
    },
    {
      id: 'vip-dinner',
      title: 'Jantar Gastronômico Premium',
      subtitle: 'Uma noite inesquecível com nossa especialista em gastronomia',
      image: '/images/experiences/wine.jpg',
      modelName: 'Sommelier Experience',
      modelDescription: 'Especialista em gastronomia e vinhos com formação internacional e experiência em restaurantes estrelados Michelin.',
      modelProfileImage: '/images/experiences/wine.jpg',
      ticketsSold: 19,
      totalTickets: 100,
      raffleTimeRemaining: '10 dias 3 horas',
      daysRemaining: 10,
      isNew: true,
      heroImage: '/images/experiences/wine.jpg',
      parallaxBackground: '/images/experiences/cocktail.jpg',
      longDescription: 'Um jantar exclusivo em um dos restaurantes mais renomados do país, com menu degustação harmonizado e preparado especialmente para a ocasião. Desfrute de uma noite de alta gastronomia acompanhado por nossa especialista em vinhos que compartilhará curiosidades e histórias sobre cada rótulo selecionado.',
      contentPreviews: [
        { title: 'Recepção Exclusiva', thumbnail: '/images/experiences/wine.jpg' },
        { title: 'Menu Degustação', thumbnail: '/images/experiences/cocktail.jpg' },
        { title: 'Harmonização', thumbnail: '/images/experiences/boudoir.jpg' },
        { title: 'Experiência Sensorial', thumbnail: '/images/experiences/gatsby.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/wine.jpg',
      raffleMainPrizeDescription: 'Jantar gastronômico exclusivo com harmonização premium em restaurante renomado',
      features: [
        { title: 'Gastronomia Premium', description: 'Menu exclusivo preparado por chef renomado', icon: '/images/icons/chef.svg' },
        { title: 'Harmonização Especializada', description: 'Vinhos selecionados para cada etapa do menu', icon: '/images/icons/conversation.svg' },
        { title: 'Ambiente Reservado', description: 'Experiência em área privativa do restaurante', icon: '/images/icons/privacy.svg' },
      ]
    },
    {
      id: 'tropical-retreat',
      title: 'Retiro de Bem-Estar Premium',
      subtitle: 'Experiência de renovação com nossa especialista em wellness',
      image: '/images/experiences/poker.jpg',
      modelName: 'Wellness Expert',
      modelDescription: 'Especialista em bem-estar com certificação internacional em práticas de yoga, meditação e técnicas de relaxamento.',
      modelProfileImage: '/images/experiences/poker.jpg',
      ticketsSold: 85,
      totalTickets: 100,
      raffleTimeRemaining: '1 dia 6 horas',
      daysRemaining: 1,
      isNew: false,
      heroImage: '/images/experiences/poker.jpg',
      parallaxBackground: '/images/experiences/gatsby.jpg',
      longDescription: 'Um fim de semana em resort exclusivo com programação personalizada de bem-estar incluindo yoga, meditação, alimentação saudável e atividades ao ar livre. Nossa especialista irá guiar todas as práticas, oferecendo dicas personalizadas e técnicas que você poderá incorporar em seu dia a dia.',
      contentPreviews: [
        { title: 'Sessão de Yoga', thumbnail: '/images/experiences/poker.jpg' },
        { title: 'Nutrição Consciente', thumbnail: '/images/experiences/gatsby.jpg' },
        { title: 'Meditação Guiada', thumbnail: '/images/experiences/escape.jpg' },
        { title: 'Práticas de Bem-estar', thumbnail: '/images/experiences/qa.jpg' },
      ],
      raffleMainPrizeImage: '/images/experiences/poker.jpg',
      raffleMainPrizeDescription: 'Fim de semana completo de bem-estar em resort de luxo com programação exclusiva',
      features: [
        { title: 'Práticas Exclusivas', description: 'Sessões personalizadas de yoga e meditação', icon: '/images/icons/yoga.svg' },
        { title: 'Nutrição Consciente', description: 'Refeições preparadas por chef especializado em alimentação funcional', icon: '/images/icons/food.svg' },
        { title: 'Acomodação Premium', description: 'Suíte exclusiva em resort 5 estrelas com todas as comodidades', icon: '/images/icons/hotel.svg' },
      ]
    }
  ];
}); 