export default defineEventHandler(() => {
  return [
    {
      id: 'trilha-jaragua',
      title: 'Trilha Íntima no Pico do Jaraguá + Chá da Tarde Proibido',
      subtitle: 'Para quem quer adrenalina e intimidade com vista privilegiada',
      image: '/images/sorteios/jaragua-sunset.jpg',
      modelName: 'Guia Aventureira',
      modelDescription: 'Modelo com experiência em trilhas e aventuras ao ar livre, conhecedora dos melhores caminhos e pontos secretos do Pico do Jaraguá, especializada em criar momentos inesquecíveis em meio à natureza.',
      modelProfileImage: '/images/sorteios/aventureira-profile.jpg',
      ticketsSold: 78,
      totalTickets: 100,
      raffleTimeRemaining: '3 dias 14 horas',
      daysRemaining: 3,
      isNew: true,
      heroImage: '/images/sorteios/jaragua-vista.jpg',
      parallaxBackground: '/images/sorteios/chale-sunset.jpg',
      longDescription: 'Uma experiência única no Pico do Jaraguá, com horário escolhido para pegar o pôr-do-sol com vista 360º de São Paulo. A trilha secreta pela Cachoeira do Silêncio oferece mais privacidade em uma caminhada leve de 40 minutos. O kit aventura inclui lanterna com luz suave para brincadeiras no escuro, canga térmica com bolso secreto e binóculos com mensagens românticas gravadas. Após a trilha, um chá da tarde especial em um chalé rústico nos arredores do parque, com cardápio afrodisíaco incluindo chá de gengibre com mel silvestre, morangos banhados em chocolate meio amargo e canapés em formato de coração. A experiência inclui o jogo "Verdadeiro ou Desafio" com perguntas picantes e massagem com óleo aquecido. Finalmente, a noite termina em um Airbnb temático "Chalé do Guarda-florestal" na Zona Oeste, com varanda com vista para a serra, lareira a lenha, banheira de hidromassagem com água termal simulada e uma rede de casal suspensa no quarto.',
      contentPreviews: [
        { title: 'Trilha Secreta', thumbnail: '/images/sorteios/jaragua-trilha.jpg' },
        { title: 'Chá da Tarde Proibido', thumbnail: '/images/sorteios/cha-tarde.jpg' },
        { title: 'Chalé Exclusivo', thumbnail: '/images/sorteios/chale-interno.jpg' },
        { title: 'Vista Panorâmica', thumbnail: '/images/sorteios/vista-panoramica.jpg' },
      ],
      raffleMainPrizeImage: '/images/sorteios/jaragua-premio.jpg',
      raffleMainPrizeDescription: 'Experiência completa de trilha no Pico do Jaraguá, chá da tarde especial e noite no chalé temático',
      features: [
        { title: 'Trilha Exclusiva', description: 'Caminho alternativo privativo com vista panorâmica', icon: '/images/icons/mountain.svg' },
        { title: 'Chá Afrodisíaco', description: 'Cardápio especial com ingredientes estimulantes', icon: '/images/icons/food.svg' },
        { title: 'Chalé Romântico', description: 'Acomodação com lareira e banheira de hidromassagem', icon: '/images/icons/hotel.svg' },
      ]
    },
    {
      id: 'drive-in-sensual',
      title: 'Drive-in Sensual + Suíte Cinema Paradiso',
      subtitle: 'Para quem quer privacidade com clima de filme proibido',
      image: '/images/sorteios/drive-in-vintage.jpg',
      modelName: 'Cinéfila Sedutora',
      modelDescription: 'Modelo apaixonada por cinema clássico e atmosferas vintage, especialista em criar experiências imersivas que misturam nostalgia e sensualidade.',
      modelProfileImage: '/images/sorteios/cinema-modelo.jpg',
      ticketsSold: 65,
      totalTickets: 100,
      raffleTimeRemaining: '5 dias 8 horas',
      daysRemaining: 5,
      isNew: true,
      heroImage: '/images/sorteios/drive-in-night.jpg',
      parallaxBackground: '/images/sorteios/cinema-suite-ambient.jpg',
      longDescription: 'A experiência acontece no Autocine Santana (Zona Norte) ou Drive-in da Mooca (região leste), com telões gigantes, som no rádio do carro e serviço de jantar no carro incluindo taça de vinho e fondue de chocolate. Antes do filme, ela recebe um "kit cinema proibido" contendo máscara de seda, luva de veludo e um "ingresso dourado" com mensagem provocante. O filme é assistido no banco de trás, convertido em "poltrona premium" com cobertores e almofadas. Durante a sessão, vocês participam do jogo "cena quente ou cena fria", onde ela escolhe quando dar um beijo ou fazer uma provocação. Após o cinema, a experiência continua na "Suíte Cine Private" em Vila Madalena ou Itaim Bibi, decorada com home theater e poltronas reclináveis, parede de LED com efeito de telão, itens anos 50 como posters de filmes clássicos e pipoqueira vintage, além de uma cama redonda com cabeceira em forma de claquete. O toque final inclui uma caixa de filmes antigos com "rolo secreto" contendo fotos sensuais da modelo.',
      contentPreviews: [
        { title: 'Drive-in Noturno', thumbnail: '/images/sorteios/drive-in-screen.jpg' },
        { title: 'Kit Cinema Proibido', thumbnail: '/images/sorteios/kit-cinema.jpg' },
        { title: 'Suíte Cinema', thumbnail: '/images/sorteios/cinema-suite.jpg' },
        { title: 'Jantar no Carro', thumbnail: '/images/sorteios/fondue.jpg' },
      ],
      raffleMainPrizeImage: '/images/sorteios/drive-in-premio.jpg',
      raffleMainPrizeDescription: 'Noite completa de drive-in sensual seguida de experiência na suíte cinema temática',
      features: [
        { title: 'Cinema Privativo', description: 'Sessão exclusiva no banco de trás com serviço especial', icon: '/images/icons/vip.svg' },
        { title: 'Jogo Sensual', description: 'Dinâmica de "cena quente ou cena fria" durante o filme', icon: '/images/icons/game.svg' },
        { title: 'Suíte Temática', description: 'Ambiente decorado com tema de cinema clássico', icon: '/images/icons/hotel.svg' },
      ]
    },
    {
      id: 'standup-airbnb',
      title: 'Stand-up Exclusivo + Airbnb Aconchegante',
      subtitle: 'Risadas, intimidade e uma noite incrível em um refúgio acolhedor',
      image: '/images/sorteios/workshop-gourmet.jpg',
      modelName: 'Artista Premium',
      modelDescription: 'Modelo encantadora que eleva cada momento a uma experiência artística única. Especialista em criar ambientes de conexão genuína, combina sensibilidade estética e conversas cativantes para transformar um encontro comum em uma obra de arte experiencial personalizada.',
      modelProfileImage: '/images/sorteios/chef-modelo.jpg',
      ticketsSold: 85,
      totalTickets: 100,
      raffleTimeRemaining: '2 dias 5 horas',
      daysRemaining: 2,
      isNew: true,
      heroImage: '/images/sorteios/workshop-luxo.jpg',
      parallaxBackground: '/images/sorteios/suite-desejo-ambiente.jpg',
      longDescription: '1. A Chegada: Onde Estranhos Viram Cúmplices\n\nVocê não entra num clube de comédia—você mergulha num cantinho escondido da cidade onde o ar vibra de expectativa. A porta no subsolo não tem placa, mas as risadas que escapam pelas paredes entregam o lugar. Alguém te recebe pelo nome, não por lista, mas porque hoje você também faz parte do show. Seu lugar não é só VIP; é o ponto onde o olhar do comediante cruza com o seu no meio da piada, onde você troca um sorriso com um desconhecido e percebe que os dois estão com lágrimas nos olhos de tanto rir.\n\n2. Os Drinks Não São Servidos—São Parte da Piada\n\nO primeiro drink chega com um sorriso: "Esse se chama \'O Preparo\'. Bebe devagar—o punchline vem aí." Cada rodada é uma surpresa, uma brincadeira líquida que derrete o gelo entre vocês dois. A comida? Pequenos sabores que aparecem na hora certa, como um alívio cômico entre uma história e outra.\n\n3. A Caminhada Que Virá Depois\n\nQuando as luzes do palco se apagam, a noite não acaba—ela só muda de tom. Vocês saem juntos, sem planejar, guiados pelo ritmo da cidade. Ruas de paralelepípedo, muros pixados que contam segredos, uma lua cheia que parece ter saído de uma piada ruim (e alguém vai fazer essa piada, com certeza). Não há roteiro, só aquele frio na barriga de quem não sabe o que vem depois, mas já sabe que vai ser bom.\n\n4. O Lugar Onde Tudo—ou Nada—Pode Acontecer\n\nO Airbnb não é só um espaço: é um convite. Luzes baixas que deixam o risado mais íntimo, uma playlist que mistura Elis Regina com stand-up, um sofá que vira palco pra histórias que não foram contadas no show. Aqui, vocês podem ser plateia um do outro, ou atores, ou só duas pessoas que descobriram que uma noite pode ser um filme—se você deixar ela rolar sem cortes.',
      contentPreviews: [
        { title: 'Show Exclusivo', thumbnail: '/images/sorteios/chef-cooking.jpg' },
        { title: 'Mesa VIP', thumbnail: '/images/sorteios/degustacao-casal.jpg' },
        { title: 'Refúgio do Riso', thumbnail: '/images/sorteios/suite-desejo.jpg' },
        { title: 'Jogos de Conexão', thumbnail: '/images/sorteios/hidro-banheira.jpg' },
      ],
      raffleMainPrizeImage: '/images/sorteios/workshop-premio.jpg',
      raffleMainPrizeDescription: 'Experiência completa de stand-up comedy exclusivo seguida de uma noite encantadora em um Airbnb temático especialmente preparado',
      features: [
        { title: 'Comedy VIP', description: 'Show exclusivo com a artista, mesa reservada e drinks premium personalizados', icon: '/images/icons/chef.svg' },
        { title: 'Jornada Sensorial', description: 'Transição mágica entre o humor e a intimidade em um percurso encantador', icon: '/images/icons/mountain.svg' },
        { title: 'Refúgio Encantado', description: 'Ambiente temático com experiências exclusivas de conexão e relaxamento', icon: '/images/icons/hotel.svg' },
      ]
    },
    {
      id: 'fofoca-seducao',
      title: 'Encontro de Fofoca & Sedução',
      subtitle: 'Segredos, desejos e provocações em uma noite exclusiva',
      image: '/images/sorteios/fofoca-vintage.jpg',
      modelName: 'Confidente Sedutora',
      modelDescription: 'Modelo especialista em criar momentos de intimidade verbal e conexão emocional, mestre na arte da conversa provocante e da troca de confidências.',
      modelProfileImage: '/images/sorteios/fofoca-modelo.jpg',
      ticketsSold: 60,
      totalTickets: 100,
      raffleTimeRemaining: '7 dias 12 horas',
      daysRemaining: 7,
      isNew: true,
      heroImage: '/images/sorteios/fofoca-elegante.jpg',
      parallaxBackground: '/images/sorteios/refugio-luxo.jpg',
      longDescription: 'Imagine uma noite exclusiva e íntima, onde a modelo participa de uma conversa secreta com você e outros membros selecionados, criando um ambiente de confiança, diversão e desejo. Tudo começa com uma troca de mensagens divertidas e provocantes, que evoluem para uma conversa mais profunda, recheada de fantasias, histórias e segredos. Para elevar o clima, haverá uma sessão de perguntas e respostas que despertam desejos ocultos, tudo com uma atmosfera de confidencialidade e exclusividade. Após a conversa virtual, você, juntamente com a modelo, será convidado a fechar a noite na suíte de um Airbnb premium na região de São Paulo - uma piscina privativa, decoração moderna e iluminação suave, preparada especialmente para um encontro inesquecível. A suíte "O Refúgio Secreto" é um espaço sofisticado, com decoração moderna, iluminação intimista, mobiliário de luxo, velas aromáticas, quadros sensuais, uma poltrona de couro e uma cama king size confortável. Inclui ainda uma área com espelhos, um lounge com bar de drinks e puffs para relaxar, criando o ambiente perfeito para trocar olhares e potencializar a sensualidade.',
      contentPreviews: [
        { title: 'Conversa Privativa', thumbnail: '/images/sorteios/fofoca-conversa.jpg' },
        { title: 'Jogo de Perguntas', thumbnail: '/images/sorteios/perguntas-intimas.jpg' },
        { title: 'Refúgio Secreto', thumbnail: '/images/sorteios/refugio.jpg' },
        { title: 'Lounge com Bar', thumbnail: '/images/sorteios/bar-lounge.jpg' },
      ],
      raffleMainPrizeImage: '/images/sorteios/fofoca-premio.jpg',
      raffleMainPrizeDescription: 'Experiência exclusiva de confidências e sedução seguida de encontro no refúgio secreto',
      features: [
        { title: 'Conversa Sensual', description: 'Troca de histórias, desejos e provocações em ambiente seguro', icon: '/images/icons/chat.svg' },
        { title: 'Dinâmica de Perguntas', description: 'Jogo provocante que desperta desejos ocultos', icon: '/images/icons/game.svg' },
        { title: 'Suíte Premium', description: 'Espaço sofisticado com bar privativo e decoração sensual', icon: '/images/icons/hotel.svg' },
      ]
    }
  ];
});